[build]
builder = "node"

[phases]
  [phases.install]
  commands = [
    "npm ci"  # Install dependencies
  ]

  [phases.build]
  commands = [
    "npx prisma generate",  # Generate Prisma client
    "next build"  # Build the Next.js application
  ]

  [phases.start]
  commands = [
    "npx next start -p 3000"  # Start the Next.js server
  ]
